# Generated by Django 5.2.1 on 2025-06-17 04:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TrainingPlan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='例: 3ヶ月ダイエット', max_length=255, verbose_name='プラン名')),
                ('goal', models.CharField(help_text='例: 体重を5kg減らす、フルマラソンを完走する', max_length=255, verbose_name='具体的な目標')),
                ('exercises', models.CharField(help_text='例: ランニング、水泳、筋トレ、ヨガ、インナーマッスルトレーニング', max_length=500, verbose_name='運動内容')),
                ('frequency', models.CharField(help_text='例: 週3回(月・水・金）、または毎日', max_length=255, verbose_name='実施頻度')),
                ('start_date', models.DateField(verbose_name='開始日')),
                ('end_date', models.DateField(verbose_name='終了日')),
                ('plan', models.JSONField(help_text='AIによって生成された各日付の運動内容(JSON配列)', verbose_name='AI生成プラン詳細')),
                ('status', models.CharField(default='active', help_text='例: active, completed, archived', max_length=50, verbose_name='プランステータス')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='作成日時')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新日時')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='training_plans', to=settings.AUTH_USER_MODEL, verbose_name='所有ユーザー')),
            ],
            options={
                'db_table': 'training_plans',
            },
        ),
        migrations.CreateModel(
            name='TrainingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('session_date', models.DateField()),
                ('completed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True)),
                ('training_plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='training.trainingplan')),
            ],
            options={
                'db_table': 'training_sessions',
            },
        ),
    ]
